### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by dadmor** [dev-javascript/string-to-react-component#1]
as a subject after yarn dev

`lib/cjs/strintToReact.js:16:1`
`lib/cjs/index.js:8:45`

**Comment by dev-javascript** [comment]
@dadmor, thanks for asking. this plugin is not designed for server side rendering, however there is a tricky solution since version 3.0.2 :
```
function App() {
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    setIsMounted(true);
  }, []);
  if (isMounted == false) {
    return null;
  } else {
    return (
      <StringToReactComponent>
        {`(props)=>{
           ...
         }`}
      </StringToReactComponent>
    );
  }
}
```
for older versions, you also need to load the above-mentioned `StringToReactComponent` component lazily.

**Comment by dev-javascript** [comment]
Version `4.0.0` works perfectly and `lazy`|`dynamic` loading is not necessary.
