### ISSUE TITLE
rendering tsx syntax

### ISSUE THREAD

**Issue by adnanjpg** [dev-javascript/string-to-react-component#3]
In a project I'm working on, I have a code editor where a user can input `tsx` code and have a preview of their output.

I am using this package for the preview, but the problem I'm facing is this package not accepting `ts` type annotations or interface definitions syntax.

here's a codesandbox example I've put together to demonstrate what does / does not work.

https://codesandbox.io/s/affectionate-wood-rswm79?file=/src/App.tsx:0-744

Is this problem in the scope of this package?

**Comment by adnanjpg** [comment]
I am able to render the code by wrapping it with 

```tsx
import * as ts from "typescript";

const tsToJs = (content: string) => {
  let result = ts.transpileModule(content, {
    compilerOptions: {
      jsx: ts.JsxEmit.React,
      module: ts.ModuleKind.CommonJS
    }
  });
  return result.outputText;
};
```

do you think this belongs inside the package, or should we just put this in the readme?

**Comment by dev-javascript** [comment]
Hello thanks for asking

This can be done with `babelOptions` prop

```
    return (
      <StringToReactComponent
        babelOptions={{
          presets: [["typescript", { allExtensions: true, isTSX: true }]]
        }}
      >
        {`
          () => {
            const MyOtherComp = (props: { message: string }) => {
              return <span>My Other Comp says {props.message}</span>
            }
            return <p>code3 works <MyOtherComp message={"hello"}/></p>
          }
        `}
      </StringToReactComponent>
    );
```

**Comment by adnanjpg** [comment]
thanks, im gonna add this to the README and send a pr
